name: "setup-swift"
description: "Set up a specific version of Swift"
inputs:
  swift-version:
    description: "The version of Swift to set up"
    required: true
    default: "5.10.1"
runs:
  using: "node20"
  main: "dist/index.js"
